### ISSUE TITLE
Expand on caveats

### ISSUE THREAD

**Issue by stefanocoretta** [many-speech-analyses/many_analyses#145]
Expand bullet-point list of caveats in RR.

**Comment by troettge** [comment]
Don't understand these ones? can you add some infos? 
- With this study, we can suggest that at a minimum this is the between-team variability, but need more studies like this one.
TR: what do you mean a minimum? could be a maximum, could be average.

- The focus is on quantitative data analysis, so that we expect the issues raised here to apply differently or not at all to qualitative data analysis.
TR: not sure this is a discussion point relevant to the journal. Its also not a caveat, more like an outlook (which we could add)

- We have not investigated researcher positionality, which is known to be an important factor.
- TR: Whats researcher positionality

**Comment by stefanocoretta** [comment]
By minimum, I mean that there is AT LEAST that much variability between teams, but maybe there is even more variability.

As for applying to qualitative research, I see it as a limitation on generalisability: it might apply to quantitative research, but not to qualitative research which has to be investigated on its own right. Which is very important point to make.

As for researcher's positionality, it is "The recognition and declaration of one’s own position in a piece of academic work" (https://emj.bmj.com/content/35/5/323), but I can deal with it later myself, so don't worry.
